spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project-manager-600?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true